version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.11.4
    ports:
      - "4572:4572"
    environment:
      SERVICES: s3
      DATA_DIR: /data
      AWS_DEFAULT_REGION: eu-west-3
    volumes:
      - type: volume
        source: localstack
        target: /data
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exhibitions

    ports:
      - "3307:3307"
 #   expose:
  #    - "3306"
    restart: unless-stopped
    networks:
      - mynet

  your-application:
    build: .

   #   context: .
  #    dockerfile: Dockerfile
   # volumes:
  #    - /app:/app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - mynet

volumes:

  localstack: {}
  your-application: {}

networks:
  mynet:
    driver: bridge
